// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://joxwqyfejcxqvfvnjiac.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpveHdxeWZlamN4cXZmdm5qaWFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUzMzgzODEsImV4cCI6MjA2MDkxNDM4MX0.4ZkXay1SRsEXDUh07XTRw-a1I8GwK9lhUyYSpVb8VkM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);